### ISSUE TITLE
Dark theme is not supported on rocketchat 3.8.0 (development) 

### ISSUE THREAD

**Issue by acuconfdev** [pbaity/rocketchat-dark-mode#81] opened 2020-11-02 02:59 UTC
**Describe the bug**
Dark theme is not supported on rocketchat 3.8.0 (development) 

**To Reproduce**
1. Install RocketChat 3.8.0 (Development)
2. Click on 'Administration-Layout-Custom CSS'
4. Set the contents of dark-mode.css
5. click on Custom Scripts > Custom Script for Logged In Users
6. Set the contents of dark-mode-toggle.js
7. Save changes
8. No changes in the theme . Not even the Dark / Light button doesnt appear

**Expected behavior**
Toggle Theme button appears and User should be able to set Dark / Light themes

**Desktop (please complete the following information):**
 - OS: WSL Ubuntu 20.04
 - Desktop Version Windows 10 - 20H2
 - Browser : chrome 
 - Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by tripout** [comment] 2020-11-02 22:07
Can confirm, Looks like the Light/Dark toggle button is missing.

Using 3.8.0-develop from a docker-compose file.

**Comment by bkraul** [comment] 2020-11-05 21:01
This has been already reported on #80. Working (very slowly) on a PR, but will need a 3.8.0 branch created by @pbaity .

**Comment by pbaity** [comment] 2020-11-09 16:48
Sorry for the delay in getting to these. I've created a [3.8.0 branch](https://github.com/pbaity/rocketchat-dark-mode/tree/3.8.0). 

Closing this issue since it's a duplicate of #80, we can track the issue and progress towards a PR there.

**Closed by pbaity** 2020-11-09 16:48 UTC
