### ISSUE TITLE
Support for 4.7.0

### ISSUE THREAD

**Issue by bkraul** [pbaity/rocketchat-dark-mode#178] opened 2022-04-20 18:13 UTC
**Is your feature request related to a problem? Please describe.**
With the release of 4.7.0 develop, an incompatibility with the theme/mode seems to exist. This is the current look of the applied dark theme:

![image](https://user-images.githubusercontent.com/14616851/164295656-f446e10b-e100-49b9-9f0e-03b431121b97.png)

**Describe the solution you'd like**
Better support for 4.7.0

**Describe alternatives you've considered**
Considered modifying the script to account for any new clases, but it has proved ineffective (without the full understanding of how it is addressed).

**Comment by TBG-FR** [comment] 2022-06-16 12:38
Do you still experience this ? I couldn't reproduce it

**Comment by bkraul** [comment] 2022-06-16 12:55
With later versions 4.7.x+ it seems it displays better, but there are still issues, especially with the Administration UI:

![image](https://user-images.githubusercontent.com/14616851/174074332-81a79455-6ad3-4cdf-a08d-5b7b769cf5d8.png)

**Comment by pbaity** [comment] 2022-06-17 16:14
@bkraul I just saw that I originally intended to fix this in early May - so sorry I didn't. That weekend ended up being an ER trip when one of my kids got sick 😅 Thanks to @TBG-FR for picking it up though.

Fixed by #185. If anybody sees the issue reoccur just reopen this issue!

**Closed by pbaity** 2022-06-17 16:14 UTC
