### ISSUE TITLE
Toggle button not visible on 3.10.3

### ISSUE THREAD

**Issue by mmgoilf** [pbaity/rocketchat-dark-mode#108] opened 2021-01-15 17:27 UTC
**Describe the bug**
On 3.10.3 the toggle button is no longer visible.

**To Reproduce**
1. Add CSS
2. Try to toggle dark mode

**Expected behavior**
Toggle button appears

**Desktop (please complete the following information):**
 - OS: Windows 10, arch linux
 - Browser, firefox, and using rocketchat desktop app
 - Version: server 3.10.3

**Additional context**
_I am also making my own custom CSS for my server, if any of the developers of this would be willing to message with me, I have questions about things I can't figure out how to fix in my own CSS._

**Comment by pbaity** [comment] 2021-01-18 15:51
@mmgoilf Can you confirm you have the most recent version of [dark-mode-toggle.js](https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode-toggle.js) and see if this issue persists? Usually this problem was caused when the class name of the top-of-sidebar button group changed, but hopefully we addressed that issue in #103.

Also, I can help you with your CSS as I have time. I'd recommend is cloning this repository or creating your own for your changes, and you can open issues that I can help with.

**Comment by bkraul** [comment] 2021-01-18 18:28
Make sure your `dark-mode-toggle.js` references has this as it's sideBar:

**Comment by mmgoilf** [comment] 2021-01-19 14:15
> @mmgoilf Can you confirm you have the most recent version of [dark-mode-toggle.js](https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode-toggle.js) and see if this issue persists? Usually this problem was caused when the class name of the top-of-sidebar button group changed, but hopefully we addressed that issue in #103.

Yes, I just tried the most recent version of the CSS and JS again.

> Also, I can help you with your CSS as I have time. I'd recommend is cloning this repository or creating your own for your changes, and you can open issues that I can help with.

 Originally I made custom CSS from scratch, but got sick of it constantly breaking every time rocketchat updated, so I started using this as a template: https://github.com/linusg/rocketchat-dark/blob/master/style.css . I just added my own custom background to match the theme of my server, and tried to fix some things that are still broken in this CSS. Unfortunately in the most recent updates, a lot of rules have "!important" added to it, which makes it seemingly impossible to override these kinds of rules: 

![Clipboard - January 19, 2021 3 07 PM](https://user-images.githubusercontent.com/42281789/105045322-14620980-5a68-11eb-97f7-0696fbe8fb9a.png)

Keep in mind I'm new to CSS, I first started learning when making the custom CSS. There might be a easy way to override this that I haven't learned. I read about higher specificity through "rule {", ".rule {" and "#rule {", but that didn't seem to work. I also read that using "!important" is generally bad, so I don't understand why they are using it so much, especially when it interferes with custom CSS.
 
 A lot of stuff in that person's CSS is also still white and a work in progress, I think due to how things like the user info panel and the admin page use the same rules for the background/text color. I remember the admin page was the most frustrating thing to try to add custom CSS to, so likely this person just wanted to leave it white for now. 
 
 Something else I can't figure out is how to get rid of the white border line that appears on the top panel:
 
![Clipboard - January 19, 2021 2_56 PM](https://user-images.githubusercontent.com/42281789/105044078-95b89c80-5a66-11eb-8243-c89eb7a2acad.png)

Originally these white border lines used a "border-bottom" rule that was easy to fix. Now it is using something else. Very frustrating. 

Something that may help me, is if there is a way to disable the JS toggle for your dark CSS, so I can more easily analyze how you made yours work, and mix and match it with my own. Unfortunately I have 0 experience with JS (willing to learn though).

If you have somewhere I could message you about this, that would be nice, as I don't want to clutter this issue with posts about my own CSS problems. I am very grateful you are willing to help me at all. I hope to not just be an annoyance as someone new to CSS and possibly not knowing obvious ways to fix things.

**Comment by mmgoilf** [comment] 2021-01-19 14:15
> 
> 
> Make sure your `dark-mode-toggle.js`, `addDarkModeToggle()` function references has this as it's `sidebarToolbar` value:
> 
> ```js
> const sidebarToolbar = $('.rcx-sidebar-topbar .rcx-button-group').first();
> ```
> 
> It's around line 44.

Yes I checked, still didn't work.

**Comment by TBG-FR** [comment] 2021-01-26 10:24
Encountering the same issue with 3.10.4 today, while yesterday the button was visible... 

However, if in another tab, in the Admin panel, I add somethings to the custom JS and I save it, the button appears on the first tab... Looks like it's an "first load" issue then, I'm trying to identify the culprit in the code, I'll keep you updated ;)

**Comment by TBG-FR** [comment] 2021-01-29 10:48
After some hours (days) of investigation, I still struggle to find the culprit... At some point I thought it was an issue related to how RocketChat parses custom scripts (there is a similar issue with CSS : https://github.com/RocketChat/Rocket.Chat/issues/19405 ) but I'm not 100% sure.

Could this be that something changed in the RocketChat page loading process ?
Because when it happens, I see the toggle button and then it quickly disappears, during the loading

**Comment by adocampo** [comment] 2021-02-01 09:48
Today I've updated from 3.7.0 to 3.11 and toggle button has disappeared as well

**Comment by nvp2211** [comment] 2021-02-01 19:45
I got the same issue and did a temporary "hack" by adding text to side navigation footer in content like this `<span onclick="document.body.classList.toggle('dark-mode');"> dark mode</span>`

**Comment by mmgoilf** [comment] 2021-02-10 09:39
@pbaity Most of the CSS issues I finally fixed on my own, the top panel's white border I fixed on accident while getting rid of the white border for the call panel, they both use the --rcx-color-neutral-300 variable. 

The toggle switch still does not appear to work in 3.11.0.

**Comment by pbaity** [comment] 2021-02-10 13:41
@mmgoilf Great job with the CSS! Glad you were able to work it out and grow your CSS skills.

I've been too busy at work to look into the toggle switch issue, but hopefully can get to it this week or weekend.

**Comment by redzonej** [comment] 2021-02-11 18:44
> @mmgoilf Great job with the CSS! Glad you were able to work it out and grow your CSS skills.
> 
> I've been too busy at work to look into the toggle switch issue, but hopefully can get to it this week or weekend.

@pbaity this appears fixed to me now with your last commit (Using today's css files works!) The issues I still see are listed in #114 which are the online status green icon not showing and any custom user status not showing in direct messages

**Comment by SaberMage** [comment] 2021-02-21 05:35
This issue is most likely caused by React's, well, reactivity. For the time being, you can edit the custom script to fix this issue:

Under the line that reads `if(!sidebarToolbar.length) {` (near line 60), change `setTimeout(addDarkModeToggle, 250);` to `setTimeout(addDarkModeToggle, 1000);`.

As long as nothing triggers a change to the button bar, the dark mode button should remain visible. The old timing for setting the button was simply too quick, and created the button before React finished updating all elements. Because the button doesn't exist in the React code, any updates to the layout in React causes it to completely refresh to what _it knows_ should be there.

**Comment by pbaity** [comment] 2021-02-23 13:06
@SaberMage Good tip - I somehow still haven't experienced the issue of the toggle button not appearing, but if you think it'd be good to increase the default timeout to 1000, open a PR for it. I can merge it and add a note to the README about adjusting it per what you've said above.

**Comment by pbaity** [comment] 2021-03-10 23:41
Is anyone else still having this problem? I still haven't been able to recreate it, but if others are still seeing it, let's increase that timeout. I don't think a full 1-second timeout will be too big of a deal if others agree.

**Comment by brunobertoldi** [comment] 2021-03-11 11:23
It's been a while that the toggle button is working

**Comment by pbaity** [comment] 2021-03-16 19:04
Going to close this issue since that seemed to be a temporary problem. If we encounter it again we can increase the timeout.

**Closed by pbaity** 2021-03-16 19:04 UTC
